server:
  port: ${PORT:9102}
management:
  health:
    binders:
      enabled: true
spring:
  rabbitmq:
    addresses: 172.18.255.200 # RabbitMQ Host - changeme
    username: admin # username - changeme
    password: admin # password - changeme
    virtual-host: /
    ssl:
      enabled: false
    publisher-confirm-type: CORRELATED
    publisher-returns: true
  cloud:
    function:
      definition: spring-perf-test;
    stream:
      #dynamic-destination-cache-size: 10
      bindings:
        spring-cloud-stream:
          destination: spring-cloud-stream
        spring-amqp:
          destination: spring-amqp
      rabbit:
        default:
          producer:
            bindQueue: false
            declareExchange: false
          consumer:
            bindQueue: false
            declareExchange: false
            consumerTagPrefix: spring-http-perf-test
        bindings:
          spring-cloud-stream:
            producer:
              routing-key-expression: '"spring-cloud-stream"'
          spring-amqp:
            producer:
              routing-key-expression: '"spring-amqp"'